seamapi/fake-seam-connect

- public/openapi.json
- src/pages/api/devices/list_device_providers.ts
- src/route-types.ts
> feat: Add devices/list_device_providers endpoint

- .eslintrc.json
- .github/workflows/check.yml
- src/lib/database/schema.ts
- src/lib/database/seed.ts
- src/lib/database/store.ts
- src/lib/middleware/with-cors.ts
- src/lib/middleware/with-cst-or-api-key-or-publishable-key.ts
- src/lib/util/simple-hash.ts
- src/pages/api/_fake/complete_connect_webview.ts
- src/pages/api/_fake/database.ts
- src/pages/api/access_codes/get.ts
- src/pages/api/access_codes/pull_backup_access_code.ts
- src/pages/api/access_codes/unmanaged/list.ts
- src/pages/api/client_sessions/create.ts
- src/pages/api/connect_webviews/get.ts
- src/pages/api/connected_accounts/get.ts
- src/pages/api/devices/get.ts
Can remove the warnings as a separate update.
> Add standard linter and rule overrides

- src/lib/database/schema.ts
- src/lib/database/seed.ts
- src/lib/database/singleton.ts
- src/lib/database/store.ts
- src/lib/fake.ts
- src/lib/middleware/with-db.ts
- src/lib/zod/api_key.ts
- test/fixtures/get-test-database.ts
- test/fixtures/get-test-server.ts
- test/stories/seed.test.ts
* adds api key support
* is `seam_seedkey1_seedkey1` a good/memorable api key?
> fix: add api key support

- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/pages/api/access_codes/update.ts
- src/route-types.ts
- test/api/access_codes/update.test.ts
Currently blocking https://github.com/seamapi/react/pull/312, which requires the `/update` endpoint for codes.
> feat(AccessCode): add /access_codes/update

- Dockerfile
- README.md
- package-lock.json
- package.json
- src/lib/fake.ts
- src/lib/server.ts
- src/server.ts
I think it makes more sense to opt-in to the seed. This also contains a fix for docker signal handling. Otherwise the contains misbehaves and will not shutdown. And a fix so args can be passed in.
> fix: Do not pre-seed by default

- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/seed.ts
- src/lib/database/store.ts
- src/lib/middleware/with-api-key.ts
- src/lib/middleware/with-cst-or-api-key-or-publishable-key.ts
- src/lib/zod/api_key.ts
- test/api/devices/list.test.ts
* api keys work on endpoints like `/devices/list`
Required for: https://github.com/seamapi/api-docs/pull/172
> Better API Key Support

- .github/CODEOWNERS
I could add Seambot but it doesn't talk much
> Add Andrewjeska to CODEOWNERS

- public/openapi.json
- src/lib/database/store.ts
- src/lib/zod/access_code.ts
- src/route-types.ts
- test/api/access_codes/unmanaged/list.test.ts
These fields are required in the openapi spec but missing in the fake, blocking tests for the c# SDK
> add missing fields to access codes

- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/zod/action_attempt.ts
- src/pages/api/locks/lock_door.ts
- src/pages/api/locks/unlock_door.ts
- src/route-types.ts
- test/api/locks/lock_door.test.ts
- test/api/locks/unlock_door.test.ts
Adds basic functionality for `/locks/lock_door` & `/locks/unlock_door`
Not currently covered in this PR:
> basic lock unlock

- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/middleware/with-simulated-outage.ts
This is breaking the fake quick server
cc @xplato
> `simulatedWorkspaceOutages` should be JSON serializable

- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/seed.ts
- src/lib/zod/device.ts
- src/pages/api/thermostats/cool.ts
- src/route-types.ts
- test/api/thermostats/cool.test.ts
Still missing a couple from prod (https://github.com/seamapi/seam-connect/tree/main/pages/api/public/thermostats), but this brings us one endpoint closer.
> feat: add /thermostats/cool

- public/openapi.json
- src/lib/database/seed.ts
- src/pages/api/thermostats/heat.ts
- src/route-types.ts
- test/api/thermostats/heat.test.ts
Adds the /heat endpoint to match the one in real api. 
https://github.com/seamapi/seam-connect/tree/main/pages/api/public/thermostats
> feat: add /thermostats/heat endpoint

- public/openapi.json
- src/pages/api/action_attempts/get.ts
- src/pages/api/action_attempts/list.ts
- src/route-types.ts
- test/api/action_attempts/get.test.ts
- test/api/action_attempts/list.test.ts
- Add /get and /list endpoints
- Test the endpoints
- Build route types and openapi
> Add `/action_attempts/get` and `/action_attempts/list` endpoints 

- public/openapi.json
- src/pages/api/connect_webviews/list.ts
- src/route-types.ts
- test/api/connect_webviews/list.test.ts
- Add /connect_webviews/list endpoint
- Test the endpoint
> Add `/connect_webviews/list` endpoint

- public/openapi.json
- src/pages/api/access_codes/get.ts
- src/pages/api/access_codes/list.ts
- src/route-types.ts
- Add device_id and code params to /access_codes/get
- Add access_code_ids param to /access_codes/list
> Add `device_id` and `code` params to `/access_codes/get` and `access_code_ids` param to `/access_codes/list`

- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/seed.ts
- src/lib/database/store.ts
- src/lib/zod/device.ts
- src/pages/api/devices/delete.ts
- src/pages/api/devices/get.ts
- src/pages/api/devices/list.ts
- src/pages/api/devices/list_device_providers.ts
- src/route-types.ts
- test/api/devices/delete.test.ts
- test/api/devices/list.test.ts
- test/fixtures/get-test-database.ts
- Add /devices/delete endpoint
- Test the enpoint
- Add some missing params to existing /devices endpoints
> Add `/devices/delete` and some missing params to existing `/devices` endpoints

- package-lock.json
- package.json
- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/pages/api/connected_accounts/delete.ts
- src/route-types.ts
- test/api/connected_accounts/delete.ts
- Add /connected_accounts/delete
- Test the endpoint
- Update db methods
- Route types and openapi
> Add `/connected_accounts/delete` endpoint

- src/pages/api/thermostats/off.ts
- src/route-types.ts
- test/api/thermostats/off.test.ts
Matching prod api: https://github.com/seamapi/seam-connect/blob/main/pages/api/public/thermostats/off.ts
> feat: add /thermostats/off endpoint

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/zod/event.ts
- src/pages/api/access_codes/create.ts
- src/pages/api/access_codes/delete.ts
- src/pages/api/events/get.ts
- src/pages/api/events/list.ts
- src/pages/api/locks/lock_door.ts
- src/pages/api/locks/unlock_door.ts
- src/route-types.ts
- test/api/events/get.test.ts
- test/api/events/list.test.ts
- Add /events/get and */list endpoints
- Created events on access_code create/delete + lock/unlock
- Test new endpoints
> Add `/events` endpoints

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/zod/workspace.ts
- src/route-types.ts
> 118 workspacesget does not return is sandbox

- src/lib/database/seed.ts
- src/pages/api/locks/lock_door.ts
- src/pages/api/locks/unlock_door.ts
Closes https://github.com/seamapi/fake-seam-connect/issues/87
> `/locks/lock_door` and `/locks/unlock_door` should actually change `locked` state

- src/lib/database/store.ts
- src/lib/zod/access_code.ts
- src/route-types.ts
We are missing `is_one_time_use` and `is_offline_access_codes`
> include required access code properties

- src/lib/params-serializer.ts
- src/pages/api/internal/devicedb/[...path].ts
I want to move this serializer to a dedicated package.
> fix: Query params proxy to devicedb

- src/lib/database/seed.ts
Need a workspace to be sandboxed to detect whether to use fake internal endpoints or live endpoints
> feat: make workspace1 is_sandbox true

- ava.config.js
- src/pages/api/internal/phone/user_identities/create_invitations.ts
- src/pages/api/internal/phone/user_identities/get_invitation.ts
- src/route-types.ts
- test/api/internal/phone/user_identities/create_invitations.test.ts
- test/api/internal/phone/user_identities/list_endpoints.test.ts
- test/api/internal/phone/user_identities/prepare_endpoint.test.ts
- test/api/internal/sandbox/[workspace_id]/assa_abloy/_fake/redeem_invite_code.test.ts
create_invitation never returns the `invitation_code`. To get the invitation code you call `create_invitation` then you `get_invitation`. Updated fake to reflect this
> fix: create invitaiton doesn't return code

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/pages/api/workspaces/reset_sandbox.ts
- src/route-types.ts
- test/api/workspaces/reset_sandbox.test.ts
- test/fixtures/get-test-database.ts
- Add db method for resetting sandboxes
- Add the endpoint
- Test the endpoint
> Add `/workspaces/reset_sandbox` endpoint

- README.md
This reverts commit aa8399f37cfaca80c9866ac26c02a85596af8885.
> Revert "fix: Update README.md (#165)"

- src/pages/api/internal/phone/visionline/list_lock_service_codes.ts
- src/route-types.ts
- test/api/internal/phone/visionline/list_lock_service_codes.test.ts
> list lock service codes endpoint

- src/lib/util/public-mapping/public-map-endpoint.ts
- src/lib/zod/endpoints.ts
- src/pages/api/internal/phone/user_identities/list_endpoints.ts
- src/pages/api/internal/phone/user_identities/prepare_endpoint.ts
- src/route-types.ts
- test/api/internal/phone/user_identities/list_endpoints.test.ts
- test/api/internal/phone/user_identities/prepare_endpoint.test.ts
Removed assa_abloy_credential_service_id as well from public typing
> fix: create public map endpoint 

- .eslintrc.json
- src/lib/database/schema.ts
- src/lib/database/seed.ts
- src/lib/database/store.ts
- src/lib/zod/client_session.ts
- src/pages/api/client_sessions/create.ts
- src/pages/api/client_sessions/get.ts
- src/pages/api/client_sessions/get_or_create.ts
- src/route-types.ts
client sessions take an array of user_identity_ids not singular
> fix: user identity ids as string array instead of just string

- src/lib/database/seed.ts
- src/lib/fake.ts
- src/pages/api/_fake/default_seed.ts
- src/pages/api/_fake/seed.ts
- src/route-types.ts
- test/api/_fake/default_seed.test.ts
- test/api/_fake/seed.test.ts
- test/api/devices/list.test.ts
- test/api/internal/devicedb/[...path].test.ts
- test/api/internal/devicedb/devicedb_image_proxy.test.ts
- test/api/internal/phone/deactivate.test.ts
- test/api/internal/phone/user_identities/create_invitations.test.ts
- test/api/internal/phone/user_identities/get_invitation.test.ts
- test/api/internal/phone/user_identities/list_endpoints.test.ts
- test/api/internal/phone/user_identities/prepare_endpoint.test.ts
- test/api/internal/phone/visionline/list_lock_service_codes.test.ts
- test/api/internal/sandbox/[workspace_id]/visionline/_fake/load_credentials.test.ts
- test/api/internal/sandbox/[workspace_id]/visionline/_fake/redeem_invite_code.test.ts
- test/api/internal/sandbox/[workspace_id]/visionline/_fake/simulate/readers/unlock.test.ts
- test/api/thermostats/cool.test.ts
- test/api/thermostats/get.test.ts
- test/api/thermostats/heat.test.ts
- test/api/thermostats/heat_cool.test.ts
- test/api/thermostats/list.test.ts
- test/api/thermostats/off.test.ts
- test/api/thermostats/set_fan_mode.test.ts
- test/api/thermostats/update.test.ts
- test/api/workspaces/create.test.ts
- test/array-parsing.test.ts
- test/stories/seed.test.ts
- **Rename seed to seedDatabase, make seed to be a map of seeded values**
- **Add endpoint for fetching seed**
> Add `/_fake/seed/` endpoint for fetching seed

- package-lock.json
- package.json
- src/lib/database/seed.ts
- src/lib/database/store.ts
- src/lib/util/get-currently-triggering-noise-thresholds.ts
- src/lib/zod/device.ts
- src/route-types.ts
- test/api/devices/list.test.ts
Added to the `addDevice` DB method—not sure if this is the best and/or only place it should go.
> feat: Add `currently_triggering_noise_threshold_ids`

- src/pages/api/_fake/simulate_workspace_outage.ts
- src/route-types.ts
- test/api/_fake/default_seed.test.ts
- test/api/_fake/simulate_workspace_outage.test.ts
- **Add simulate workspace outage endpoint**
- **Add test**
> Add `/_fake/simulate_workspace_outage`

- src/lib/zod/action_attempt.ts
- src/pages/api/_fake/update_action_attempt.ts
- src/route-types.ts
- test/api/_fake/update_action_attempt.test.ts
- **Add /_fake/update_action_attempt, update action_attempt zod schema**
- **Add test**
> feat: Add `/_fake/update_action_attempt`

- src/lib/database/seed.ts
- src/lib/middleware/with-session-auth.ts
- src/pages/api/workspaces/get.ts
- src/types/authenticated-request.ts
- test/middleware/with-session-auth.test.ts
Closes https://github.com/seamapi/fake-seam-connect/issues/124
- **Fix withSessionAuth middleware**
- **Fix test**
> fix: Improve `withSessionAuth` middleware

- src/lib/middleware/with-access-token.ts
- src/pages/api/workspaces/list.ts
- src/types/authenticated-request.ts
- test/middleware/with-access-token.test.ts
- test/middleware/with-api-key.test.ts
Closes https://github.com/seamapi/fake-seam-connect/issues/126
- **Improve withAccessToken auth middleware**
- **Add test, fix withAccessToken**
- **Fix test/middleware/with-api-key.test.ts**
> fix: Improve `withAccessToken` auth middleware
