seamapi/fake-seam-connect

- src/lib/database/store.ts
Required as part of https://github.com/seamapi/react/issues/236, currently adding a new access code doesn't include the required errors/warnings, resulting in this error:
> Fix(AccessCode): add missing errors

- public/openapi.json
- src/pages/api/access_codes/update.ts
Previously had a `uuid()`, which fails since we're just using hardcoded ids, like `device_1`.
> fix: /access_codes/update requiring uuid

- public/openapi.json
- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/middleware/with-simulated-outage.ts
- test/api/client_sessions/get.test.ts
- test/api/devices/list.test.ts
`db.simulateWorkspaceOutage(workspace_id)` -> `db.simulateWorkspaceOutage(workspace_id, { routes: ["/devices/list" ] })`
> feat: Add route matcher for `db.simulateWorkspaceOutage`

- package-lock.json
- package.json
- src/pages/api/internal/devicedb/[...path].ts
- src/pages/api/internal/devicedb_image_proxy.ts
Axios has a known issue with vitest when running in workers. Fetch makes more sense here anyway IMO as it does not introduce a new dependency.
> feat: Use fetch to proxy response

- src/lib/zod/device.ts
- src/pages/api/thermostats/set_fan_mode.ts
- src/route-types.ts
- test/api/thermostats/set_fan_mode.test.ts
live endpoint: https://github.com/seamapi/seam-connect/blob/main/pages/api/public/thermostats/set_fan_mode.ts
Dev should just use the currently supported `fan_mode_setting`.
Live checks the manufacturer name:
```ts
const provider = getThermostatFunctionProvider(device.manufacturer_name)
if (!provider.setFanMode) {
throw new HttpException(400, {
type: "set_fan_mode_not_supported",
// TODO: Fix this the next time the file is edited.
// eslint-disable-next-line @typescript-eslint/restrict-template-expressions
message: `/thermostats/set_fan_mode does not support ${device.manufacturer_name} thermostats`,
})
}
```
Manufacturer data is missing in the fake, and seems out-of-scope for the fake anyway, where manufacturers / ids are sometimes stubbed.
> feat: add /thermostats/set_fan_mode endpoint

- src/pages/api/internal/devicedb/[...path].ts
- src/pages/api/internal/devicedb_image_proxy.ts
Using the second argument is a bit of a foot gun if one needs to allow sub-paths.
> fix: Allow constructed URLs to include paths

- src/pages/api/access_codes/delete.ts
`/access_codes/delete` wasn't actually creating the `action_attempt` it was returning. It caused issues when I wanted to poll that action attempt with `/action_attempts/get` because the action attempt wasn't actually added to the db state during access code deletion
> `/access_codes/delete` should actually create the returned `action_attempt`

- src/lib/database/store.ts
Currently we pass custom id like `john_connected_account_id` when creating a connected account in the `lib/database/seed.ts` and then associate new devices with that id but `addConnectedAccount` method wasn't assigning such ids to accounts during creation so the devices were associated with a nonexistent account ids.
> Allow passing custom id when creating connected accounts with `addConnectedAccount`

- package-lock.json
- package.json
- src/lib/util/devices.ts
- src/pages/api/devices/list.ts
- src/pages/api/events/list.ts
- test/api/devices/list.test.ts
- test/api/events/list.test.ts
- test/fixtures/get-test-server.ts
When array params are passed to the API as an empty array, the real API behavior would return no results, e.g., the logic is always `filter(r => r_ids.includes(r.id))`, the length of `r_ids` is irrelevant.
> fix: Empty array param parsing regression

- src/lib/server.ts
This is only used in Docker of if the server is run as the main process entrypoint. I am seeing possible issues with Node 20 and latest AVA. No reason to use this when controlled directly.
> fix: Bypass terminus if no signals are passed

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/zod/assa_abloy_credential_service.ts
- src/pages/api/internal/sandbox/[workspace_id]/assa_abloy/_fake/simulate/readers/list_events.ts
- src/pages/api/internal/sandbox/[workspace_id]/assa_abloy/_fake/simulate/readers/unlock.ts
- src/route-types.ts
- test/api/internal/sandbox/[workspace_id]/assa_abloy/_fake/simulate/readers/unlock.test.ts
Closes https://github.com/seamapi/fake-seam-connect/issues/136
simulate tap to unlock visionline reader
Using dummy data right now since none of the acs fake endpoints are implemented. Just to get by for mobilesdk testing
> feat: visionline simulate unlock

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/zod/invitations.ts
- src/pages/api/internal/phone/user_identities/get_invitation.ts
- src/pages/api/internal/sandbox/[workspace_id]/assa_abloy/_fake/redeem_invite_code.ts
- src/route-types.ts
- test/api/internal/phone/user_identities/prepare_endpoint.test.ts
Assa abloy endpoint is created when an invitation is first created, it gets activated when the invitation code is redeemed. This PR implements an `activateEndpoint` function and defaults `addEndpoint().is_active` to be false
> feat: activate assa abloy endpoint

- src/pages/api/internal/sandbox/[workspace_id]/visionline/_fake/redeem_invite_code.ts
- test/api/internal/sandbox/[workspace_id]/visionline/_fake/redeem_invite_code.test.ts
This is supposed to be a non-nullable field in the SDK, so it should definitely be returned
cc @ethanplee14
> include seos tsm id in response

- src/lib/zod/endpoints.ts
- src/pages/api/internal/phone/user_identities/list_endpoints.ts
- src/route-types.ts
- test/api/internal/phone/user_identities/list_endpoints.test.ts
Assa abloy endpoint doesn't have an invitation id in connect:
https://github.com/seamapi/seam-connect/blob/b1fb61c5cbde341fd22dc9aec548d24085d62e6b/lib/acs/types.ts#L62
> fix: remove invitation id from assa abloy endpoint

- src/pages/api/workspaces/create.ts
- src/route-types.ts
- test/api/workspaces/create.test.ts
It seems a bit unusual that the internal and public /workspaces/create endpoints differ regarding this name parameter, but that’s currently the case with seam-connect. For now, I’m aligning with this to ensure our Python SDK tests pass. We can look into harmonizing these endpoints on the seam-connect side as a future improvement.
> `/workspaces/create`: rename `workspace_name` to `name` param

- src/pages/api/internal/phone/visionline/list_lock_service_codes.ts
- src/route-types.ts
- test/api/internal/phone/visionline/list_lock_service_codes.test.ts
we changed lock services codes to be an array of strings instead of numbers
> fix: lock service codes as string instead of numbers

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/lib/zod/workspace.ts
- src/route-types.ts
- test/api/workspaces/get.test.ts
This PR adds `workspace.company_name` to fix PHP SDK tests that are failing because of this missing property.
> feat: Add `company_name` prop to `workspace` resource

- package-lock.json
- package.json
- src/lib/database/schema.ts
- src/lib/database/seed.ts
- src/lib/zod/device.ts
- src/route-types.ts
Workaround until https://github.com/seamapi/fake-seam-connect/issues/203
> feat: Add lock capability flags

- src/pages/api/_fake/update_action_attempt.ts
- src/route-types.ts
- test/api/_fake/update_action_attempt.test.ts
- **Adjust /_fake/update_action_attempt endpoint to support updating action attempt to pending**
- **Update the test**
> feat: add support for updating action attempt status to `pending` via `/_fake/update_action_attempt`

- src/lib/middleware/with-api-key.ts
- src/pages/api/devices/list.ts
- src/types/authenticated-request.ts
- test/middleware/with-api-key.test.ts
- **Improve withApiKey auth middleware**
- **ci: Format code**
- **Test**
> fix: Improve `withApiKey` auth middleware

- src/lib/middleware/with-publishable-key.ts
- src/lib/middleware/with-route-spec.ts
- src/pages/api/client_sessions/create.ts
- src/route-types.ts
- src/types/authenticated-request.ts
closes #228 
Adds the new auth method, also updates `/client_sessions/create` to use auth array (same as real)
> feat: add publishable_key_auth

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/pages/api/seam/bridge/v1/bridge_client_sessions/regenerate_pairing_code.ts
- src/route-types.ts
- test/api/bridge/v1/bridge_client_sessions/regenerate_pairing_code.test.ts
Closes https://linear.app/seam/issue/ACS-476/implement-seambridgev1bridge-client-sessions-endpoints-in-fake-seam
> feat(bridge): add /regenerate_pairing_code endpoint

- src/lib/database/schema.ts
- src/lib/database/store.ts
- src/pages/api/seam/bridge/v1/bridge_client_sessions/create.ts
- src/pages/api/seam/bridge/v1/bridge_client_sessions/regenerate_pairing_code.ts
- test/api/bridge/v1/bridge_client_sessions/regenerate_pairing_code.test.ts
Closes https://linear.app/seam/issue/ACS-476/implement-seambridgev1bridge-client-sessions-endpoints-in-fake-seam
Pairing code was previously hardcoded to `123456` but Pairing codes should be randomized as it's used to identify a session.
> fix(Bridge Client Session): randomize pairing_code

- src/lib/database/seed.ts
- src/lib/database/store.ts
- src/lib/zod/bridge_client_session.ts
- src/route-types.ts
- test/fixtures/get-test-database.ts
Not sure why I had it set to an `array`, but it should be a `string`, same as actual connect.
> fix(Bridge Client): set tailscale_auth_key to string

- src/lib/database/store.ts
- src/lib/zod/workspace.ts
- src/route-types.ts
- test/api/connected_accounts/get.test.ts
- test/api/connected_accounts/list.test.ts
- test/api/workspaces/create.test.ts
- **Add workspace.is_publishable_key_auth_enabled**
- **ci: Generate code**
- **Add test for connected_accounts.accepted_capabilities**
- **Add test for connected_accounts.accepted_capabilities to list**
> feat: Add workspace.is_publishable_key_auth_enabled
